steps:
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'github connection 1'
      repositoryName: '$(Build.Repository.Name)'
      tagSource: manual
      tag: $(Build.BuildNumber)
      assets: |
          $(Build.ArtifactStagingDirectory)/*
